version: "3.3"
services:
  star-tides:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - mongodb_container
    ports:
      - 5000:5000
  test:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - mongodb_container
    ports:
      - 5001:5000
    command: bash -c "cd /app && pytest -q star_tides/"
  mongodb_container:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
