version: "3.3"
services:
  # Main service. This is our actual application.
  star-tides:
    build:
      context: ./ # Context should be where the docker-compose file is located
      dockerfile: Dockerfile
    env_file: # Stores our environment variables
      - .env
    restart: always # Restarts the container if it fails
    volumes: # Mounts the codebase in at runtime so that A) we can hot reload
             # code and B) so that we don't have to docker-compose build;
             # docker-compose up every time we make a code change
      - ./:/app
    depends_on:
      - mongodb_container # depends on the database
    ports:
      - 5000:5000 # Available on host port 5000, broadcasting on container port 5000
  test: # Same as the star-tides service but used for testing the backend
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    volumes:
      - ./:/app
    depends_on: # means that docker-compose up test will start the mongodb_container service
                # before launching the test service
      - mongodb_container
    command: bash -c "cd /app && pytest star_tides/"
  mongodb_container: # Container that runs the database. This is persistent
                     # Over restarts because of the named volume. To reset
                     # the database, look up removing a named docker volume.
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
